### ISSUE TITLE
Small nit

### ISSUE THREAD

**Issue by nhrones** [aapoalas/denonomicon#10]
Page changes never start at the top of a page for me.
I use an older Windows10 laptop with Chrome browser.
When I select from the sidebar or other page change UI, It never loads the new page at the top?  Not a big thing.

Nice work by the way!  Well written and easy to consume!

**Comment by nhrones** [comment]
not important!

**Comment by aapoalas** [comment]
Hey, thank you for the feedback! I'd just copied this website base over from Deno's Manual and they had that sort of scrolling. I've now removed it from Denonomicon.
