### ISSUE TITLE
Logo

### ISSUE THREAD

**Issue by hashrock** [aapoalas/denonomicon#5]
![denonomicon](https://user-images.githubusercontent.com/3132889/186219583-a5f6360b-4b63-4c19-88b8-f2e355c486cd.svg)
![simple (1)](https://user-images.githubusercontent.com/3132889/186220353-1a0393ed-2e2a-4cc9-a8f3-638a4c5f8b73.svg)

new version :)

- avoid Reimu style

**Comment by aapoalas** [comment]
Oooh, thank you <3 Is it okay for me to copy these off of here and turn the top on into an .ico file? The lower one I'd like to add to the side-bar somehow...

How should I attribute your contribution?

**Comment by hashrock** [comment]
Feel free to convert, modify or anything you want :)

I recommend CC BY-NC-ND 4.0 for license, this is not intended to apply to you and restricts secondary users. like this:

> The logo was designed by hashrock, licensed under CC BY-NC-ND 4.0.

**Comment by aapoalas** [comment]
I have added the logo as a favicon and onto the Introduction page, together with an attribution. Additionally, I have placed the "title" graphic on the menu.

Thank you very much! <3
